using System.Collections.Generic;
using System.Linq;
using System.Text;

using Daibitx.DynamicApi.Runtime.Models;

namespace Daibitx.DynamicApi.Runtime.Templates
{
    /// <summary>
    /// Controller 代码模板
    /// </summary>
    public class ControllerTemplate
    {
        public string Generate(
            string namespaceName,
            string controllerName,
            string interfaceName,
            string routePrefix,
            ApiExplorerSettings apiExplorerSettings,
            List<MethodInfo> methods)
        {
            var sb = new StringBuilder();

            // 文件头
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            // using 声明
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();

            // 命名空间
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            // Controller 特性
            sb.AppendLine($"    [ApiController]");

            if (!string.IsNullOrEmpty(apiExplorerSettings.GroupName))
            {
                sb.AppendLine($"    [ApiExplorerSettings(GroupName = \"{apiExplorerSettings.GroupName}\")]");
            }

            if (apiExplorerSettings.IgnoreApi)
            {
                sb.AppendLine($"    [ApiExplorerSettings(IgnoreApi = true)]");
            }

            sb.AppendLine($"    [Route(\"{routePrefix}\")]");

            // Controller 类声明
            sb.AppendLine($"    public partial class {controllerName} : ControllerBase");
            sb.AppendLine("    {");

            // 字段
            sb.AppendLine($"        private readonly {interfaceName} _service;");
            sb.AppendLine();

            // 构造函数
            sb.AppendLine($"        public {controllerName}({interfaceName} service)");
            sb.AppendLine("        {");
            sb.AppendLine("            _service = service ?? throw new ArgumentNullException(nameof(service));");
            sb.AppendLine("        }");
            sb.AppendLine();

            // 方法
            foreach (var method in methods)
            {
                GenerateMethod(sb, method);
            }

            // 类结束
            sb.AppendLine("    }");

            // 命名空间结束
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("#pragma warning restore");

            return sb.ToString();
        }
        private void GenerateMethod(StringBuilder sb, MethodInfo method)
        {
            // 方法注释
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// {method.Name} 方法");
            sb.AppendLine("        /// </summary>");

            // HTTP 方法特性
            sb.AppendLine($"        [{method.HttpMethod}]");

            // 路由模板
            var routeTemplate = GenerateRouteTemplate(method);
            if (!string.IsNullOrEmpty(routeTemplate))
            {
                sb.AppendLine($"        [Route(\"{routeTemplate}\")]");
            }
            var isAsync = IsAsyncReturnType(method.ReturnType);
            // 方法签名
            sb.Append($"       public {(!isAsync ? "" : "async ")} {method.ReturnType} {method.Name}(");

            // 参数
            var parameters = new List<string>();
            foreach (var param in method.Parameters)
            {
                var paramStr = new StringBuilder();

                if (!string.IsNullOrEmpty(param.BindingSource))
                {
                    paramStr.Append($"{param.BindingSource} ");
                }

                paramStr.Append($"{param.Type} {param.Name}");

                if (param.IsOptional)
                {
                    paramStr.Append($" = {param.DefaultValue}");
                }

                parameters.Add(paramStr.ToString());
            }

            sb.Append(string.Join(", ", parameters));
            sb.AppendLine(")");

            // 方法体
            sb.AppendLine("        {");

            // 调用服务方法
            var args = string.Join(", ", method.Parameters.Select(p => p.Name));
            sb.AppendLine($"            return await _service.{method.Name}({args});");

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private bool IsAsyncReturnType(string returnType)
        {
            if (string.IsNullOrWhiteSpace(returnType))
                return false;

            var normalized = returnType.Trim();

            if (normalized.StartsWith("global::"))
                normalized = normalized.Substring("global::".Length);

            normalized = normalized.Replace(" ", "");

            var lower = normalized.ToLowerInvariant();

            if (lower == "system.threading.tasks.task")
                return true;

            if (lower.StartsWith("system.threading.tasks.task<"))
                return true;

            if (lower == "system.threading.tasks.valuetask")
                return true;

            if (lower.StartsWith("system.threading.tasks.valuetask<"))
                return true;

            if (lower == "task" || lower.StartsWith("task<"))
                return true;

            if (lower == "valuetask" || lower.StartsWith("valuetask<"))
                return true;

            return false;
        }


        private string GenerateRouteTemplate(MethodInfo method)
        {
            var idParam = method.Parameters.FirstOrDefault(p => p.Name.ToLowerInvariant() is "id" or "key" or "code");

            if (idParam != null && method.HttpMethod == "HttpGet")
            {
                return "{id}";
            }

            return string.Empty;
        }
    }
}